# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 08:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='attended_events',
        ),
        migrations.RemoveField(
            model_name='user',
            name='registered_events',
        ),
    ]
