# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 15:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('event_start', models.DateField()),
                ('event_end', models.DateField()),
                ('register_fee', models.PositiveIntegerField()),
                ('register_start', models.DateField()),
                ('register_end', models.DateField()),
                ('max_attend_user', models.PositiveSmallIntegerField()),
                ('event_type', models.PositiveSmallIntegerField(choices=[(1, 'DjangoGirls Seminar'), (2, 'Community Tutorial'), (3, 'Community Meetup')])),
                ('attended_users', models.ManyToManyField(related_name='attended_users', to=settings.AUTH_USER_MODEL)),
                ('registered_users', models.ManyToManyField(related_name='registered_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='%Y/%m/%d/')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Events.Event')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('study_start', models.DateField()),
                ('study_end', models.DateField()),
                ('register_fee', models.PositiveIntegerField()),
                ('register_start', models.DateField()),
                ('register_end', models.DateField()),
                ('registered_users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudyTimes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('times', models.PositiveSmallIntegerField()),
                ('attended_users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Events.Study')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
