# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 15:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='%Y/%m/%d/')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Events.Study')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudyTimesImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='%Y/%m/%d/')),
                ('studytimes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Events.StudyTimes')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
