# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0002_studyimage_studytimesimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studytimesimage',
            name='studytimes',
        ),
        migrations.AddField(
            model_name='studytimes',
            name='image',
            field=models.ImageField(blank=True, upload_to='%Y/%m/%d/'),
        ),
        migrations.DeleteModel(
            name='StudyTimesImage',
        ),
    ]
